import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ToastContainer position="top-center" closeOnClick={true} />
        <div className="flex flex-col mx-auto px-4 lg:px-28">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
